{{- if .Values.backup.enabled -}}
{{- if eq .Values.backup.provider "azure" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stardog.fullname" . }}-azurefile-bck-pvc
  namespace: {{ include "stardog.namespace" . }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}

spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: {{ include "stardog.fullname" . }}-azurefile-bck-pv
  resources:
    requests:
      storage: {{ .Values.backup.azure.storage.capacity }}
{{- end }}
{{- end }}