apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stardog.fullname" . }}-log4j
  namespace: {{ include "stardog.namespace" . }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
data:{{ if .Values.log4jConfig.override }}
  log4j2.xml: {{ toJson .Values.log4jConfig.content }}{{ else }}
  {{- (.Files.Glob "files/log4j2.xml").AsConfig | nindent 2 }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stardog.fullname" . }}-properties
  namespace: {{ include "stardog.namespace" . }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}

data:
  {{- (.Files.Glob "files/stardog.properties").AsConfig | nindent 2 }}
    pack.enabled={{ .Values.cluster.enabled }}
    {{- .Values.additionalStardogProperties | nindent 4 }}
    pack.zookeeper.address={{ if .Values.zookeeper.enabled }}{{- template "zkservers" . }}{{ else }}{{ .Values.zookeeper.addresses }}{{ end }}

{{ if .Values.oauth.enabled }}
{{ if eq .Values.oauth.azure "azure" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stardog.fullname" . }}-jwt
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}

data:
  jwt.yaml: |-
    ---
    confVersion: "1.0"
    deploymentName: {{ .Values.oauth.azure.name }}

    issuers:
      {{ .Values.oauth.azure.jwt_issuer }}:
        audience: {{ .Values.oauth.azure.audience}}
        usernameField: {{ .Values.oauth.azure.usernameField }}
        autoCreateUsers: {{ .Values.oauth.azure.autoCreateUsers }}
        allowedGroupIdentifiers: [ {{ .Values.oauth.azure.allowedGroupIdentifiers }} ] 
        algorithms:
          RS256:
            keyUrl: {{ .Values.oauth.azure.keyUrl }}
{{ end }}
{{ end }}