{{- if .Values.backup.enabled -}}
{{- if eq .Values.backup.provider "gcp" -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "stardog.fullname" . }}-gcpfile-bck-pv
  namespace: {{ include "stardog.namespace" . }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  capacity:
    storage: {{ .Values.backup.gcp.storage.capacity }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: /{{ .Values.backup.gcp.storage.path }}
    server: {{ .Values.backup.gcp.storage.ipAddress }}
{{- end }}
{{- end }}